### ISSUE TITLE
Not working for Windows

### ISSUE THREAD

**Issue by ivanjeremic** [ee92/todo-gui#1] opened 2019-08-11 11:35 UTC
On Windows the only thing I can do is adding folders, No Code Files are detected and also no Editor is opening.

**Comment by ee92** [comment] 2019-08-11 17:42
@ivanjeremic does anything show up in the sidebar after you add a folder?

I don't have a windows machine so it's hard to diagnose without having to spin up a vm but maybe you're interested to help fix or debug it? 😅

**Comment by ee92** [comment] 2019-08-11 22:06
I just ran it on a buddy's pc. Everything seemed to work fine...

@ivanjeremic can you provide the steps to reproduce the problem?

**Comment by ivanjeremic** [comment] 2019-08-12 10:35
> I just ran it on a buddy's pc. Everything seemed to work fine...
> 
> @ivanjeremic can you provide the steps to reproduce the problem?

Sorry but there are no steps I click on the + Button then I select an empty folder the folder is then in the left sidebar, but what now? If I add .js files in this folder nothing is shown inside the app, the only thing this app is doing for me is showing folders in the left sidebar without that whats in them.

**Comment by ee92** [comment] 2019-08-12 17:06
@ivanjeremic do you have any TODO comments in those files? The app only shows a list of the todos in your project. Not all files in the folder.

**Comment by ee92** [comment] 2019-08-13 17:10
Looks like a misunderstanding of how to use the app. Will update README to make it more clear. Closing this out.

**Closed as completed by ee92** 2019-08-13 17:10 UTC
Labels: invalid
